# -*- coding: utf-8 -*-
"""Stock Market Performance Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jubyMXYIwqsRQQ42dXh2RUfyae74R3d_

### **Stock Market Performance Analysis**

Proyek Analisis Kinerja Pasar Saham ini merupakan sebuah proyek yang dilakukan untuk menganalisis kinerja pasar saham dengan menggunakan data historis harga saham.

#### **Latar belakang**
Latar belakang proyek ini adalah untuk memberikan pemahaman yang lebih dalam tentang bagaimana kinerja saham-saham terkait yang terdapat dalam dataset. Data yang digunakan dalam proyek ini mencakup harga penutupan saham dari beberapa perusahaan yang aktif diperdagangkan di pasar saham. Dalam hal ini, data tersebut mencakup harga penutupan saham perusahaan seperti AAPL (Apple Inc.), MSFT (Microsoft Corporation), NFLX (Netflix, Inc.), dan GOOG (Google Inc.).

#### **Tujuan**
Tujuan utama dari proyek ini adalah untuk melakukan analisis kinerja pasar saham dan mengidentifikasi pola atau tren yang dapat memberikan wawasan berharga kepada investor dan pemangku kepentingan pasar saham. Dalam proyek ini, beberapa metode analisis yang mungkin digunakan adalah penghitungan rata-rata pergerakan, perubahan persentase harian, volatilitas, dan grafik harga saham. Tujuan akhirnya adalah untuk memberikan informasi yang berguna dalam pengambilan keputusan investasi.

Dengan proyek ini, Nanda Yuli Akhirdianto, sebagai seorang Data Analyst, berperan dalam mengumpulkan, membersihkan, dan menganalisis data pasar saham. Selain itu, Nanda juga bertanggung jawab dalam membuat visualisasi data yang jelas dan informatif, serta menyajikan temuan dan insight dari analisis tersebut.

Melalui proyek Analisis Kinerja Pasar Saham ini, diharapkan dapat memberikan pemahaman yang lebih baik tentang kinerja dan volatilitas saham-saham yang dianalisis, serta memberikan wawasan yang bermanfaat bagi para pemangku kepentingan di pasar saham.






#### **Setup**
"""

import pandas as pd
import yfinance as yf # untuk mengambil data historis saham dan informasi keuangan dari Yahoo Finance.
from datetime import datetime # untuk bekerja dg objek tanggal dan waktu

# menentukan tanggal awal dan akhir data diambil dari historis 3 bulan terakhir
start_date = datetime.now() - pd.DateOffset(months=3)
end_date = datetime.now()

# menentukan objek/perusahaan yang diambil untuk dianalisis
tickers = ['AAPL', 'MSFT', 'NFLX', 'GOOG']

df_list = [] # untuk menyimpan data yang diambil

# looping data historis kemudian disimpan ke 'df_list'
for ticker in tickers:
    data = yf.download(ticker, start=start_date, end=end_date)
    df_list.append(data)

data = pd.concat(df_list, keys=tickers, names=['Ticker', 'Date']) # menggabungkan data-data di 'df_list' menjadi Data Frame
print(data.head())

"""Pada kode di atas, adalah mengunduh data harga saham historis untuk empat perusahaan: Apple, Microsoft, Netflix, dan Google, selama tiga bulan terakhir.

Karena tanggal pada data diatas berbentuk index, kita akan mengubahnya dengan skrip berikut
"""

data = data.reset_index()
print(data.head())

"""#### **Analisa**



Selanjutnya kita lihat kinerja di pasar saham dari keempat perusahaan ini, dengan melihat grafik performa.
"""

import plotly.express as px
fig = px.line(data, x='Date',
              y='Close',
              color='Ticker',
              title="Kinerja Pasar Saham 3 Bulan Terakhir")
fig.show()

"""Dari visual diatas bisa dikatakan 'NFLX' memiliki kinerja tertinggi meskipun sempat mengalami penurunan. 'AAPL' dan 'GOOG' cukup stabil.

Selanjutnya mari kita lihat grafik faceted area, yang memudahkan untuk membandingkan kinerja berbagai perusahaan dan mengidentifikasi persamaan atau perbedaan dalam pergerakan harga saham mereka.
"""

# Grafik area ini akan menampilkan harga penutupan (Close) dari saham-saham
fig = px.area(data, x='Date', y='Close', color='Ticker',
              facet_col='Ticker',
              labels={'Date':'Date', 'Close':'Closing Price', 'Ticker':'Company'},
              title='Harga Saham untuk Apple, Microsoft, Netflix, dan Google')
fig.show()

"""Selanjutnya kita menganalisis moving average, yang memberikan cara yang berguna untuk mengidentifikasi tren dan pola pergerakan harga saham setiap perusahaan selama periode waktu tertentu, Dengan menghitung rata-rata bergerak dengan jendela 10 hari dan 20 hari, kita dapat melihat tren jangka pendek dan menengah."""

# menghitung moving average dengan jendela 10 hari dari harga penutupan (Close)
data['MA10'] = data.groupby('Ticker')['Close'].rolling(window=10).mean().reset_index(0, drop=True)
# menghitung moving average dengan jendela 20 hari dari harga penutupan (Close)
data['MA20'] = data.groupby('Ticker')['Close'].rolling(window=20).mean().reset_index(0, drop=True)

for ticker, group in data.groupby('Ticker'):
    print(f'Moving Averages for {ticker}')
    print(group[['MA10', 'MA20']])

# Selanjutnya kita visualisasikan temuan diatas, untuk pemahaman lebih terkait pergerakan yang terjadi
for ticker, group in data.groupby('Ticker'):
    fig = px.line(group, x='Date', y=['Close', 'MA10', 'MA20'],
                  title=f"{ticker} Moving Averages")
    fig.show()

"""Output menunjukkan empat grafik terpisah untuk setiap perusahaan. Saat MA10 melintas di atas MA20, hal itu dianggap sebagai sinyal bullish yang menandakan bahwa harga saham akan terus naik. Sebaliknya, ketika MA10 memotong ke bawah MA20, itu adalah sinyal bearish bahwa harga saham akan terus turun.

'Apple', 'Google', dan 'Microsoft' menunjukkan sinyal **bullish**, yang menandakan bahwa harga saham akan terus naik. Sebaliknya penurunan harga saham sempat dialami 'Netflix' periode pertengahan bulan April hingga awal Mei, dengan ditunjukkannya sinyal **bearish** (sinyal MA10 yang memotong MA20), sebelum akhirnya stabil naik.

Tujuan dari analisa ini dengan melibatkan rata-rata bergerak dengan jendela 10 dan 20 hari dari harga penutupan adalah:

1. Dengan menghitung rata-rata bergerak dengan jendela 10 hari dan 20 hari, kita dapat melihat tren jangka pendek dan menengah.
2. Rata-rata bergerak dapat membantu menghaluskan fluktuasi harian dalam harga saham, sehingga memberikan gambaran yang lebih jelas tentang tren keseluruhan. Dengan menggunakan jendela 10 hari dan 20 hari, kita dapat melihat tren yang lebih halus daripada hanya menggunakan harga penutupan harian.
3.  Rata-rata bergerak sering digunakan untuk mengidentifikasi level support (batas bawah) dan resistance (batas atas) dalam pergerakan harga saham. Ketika harga saham bergerak di atas rata-rata bergerak, itu bisa menjadi sinyal bahwa saham sedang menguat dan mencapai level resistensi. Sebaliknya, ketika harga saham bergerak di bawah rata-rata bergerak, itu bisa menjadi sinyal bahwa saham sedang melemah dan mencapai level support.
4. Persilangan antara dua rata-rata bergerak, seperti rata-rata bergerak 10 hari yang melintasi rata-rata bergerak 20 hari, dapat memberikan sinyal beli atau jual.

Selanjutnya kita perlu menganalisis volatilitas semua perusahaan. Volatilitas adalah ukuran seberapa banyak dan seberapa sering harga saham atau pasar berfluktuasi selama periode waktu tertentu.
"""

# untuk menghitung dan memvisualisasikan volatilitas (tingkat fluktuasi) dari harga penutupan (Close) stocks
data['Volatility'] = data.groupby('Ticker')['Close'].pct_change().rolling(window=10).std().reset_index(0, drop=True)
fig = px.line(data, x='Date', y='Volatility',
              color='Ticker',
              title='Volatility of All Companies')
fig.show()

"""Volatilitas mengacu pada tingkat fluktuasi atau variasi harga aset keuangan dari waktu ke waktu. Dalam konteks harga saham, volatilitas mengukur seberapa besar perubahan harga saham dari nilai rata-ratanya. Saham dengan volatilitas tinggi cenderung memiliki fluktuasi harga yang signifikan, sedangkan saham dengan volatilitas rendah cenderung memiliki fluktuasi harga yang lebih stabil.

Selanjutnya kita akan melihat korelasi antara 'Apple' dan 'Google', kita semua tahu bahwa dua perusahan ini mengembangkan dan memiliki sistem operasi (OS) terkuat, yaitu iOS dan AndroidOS, dimana kedua OS ini menjadi yang terkuat tidak hanya di Indonesia tapi juga di dunia.
"""

# membuat DataFrame dengan harga saham Apple dan Google
apple = data.loc[data['Ticker'] == 'AAPL', ['Date', 'Close']].rename(columns={'Close': 'AAPL'})
google = data.loc[data['Ticker'] == 'GOOG', ['Date', 'Close']].rename(columns={'Close': 'GOOG'})
data_corr = pd.merge(apple, google, on='Date')

# buat scatter plot untuk memvisualisasikan korelasi
fig = px.scatter(data_corr, x='AAPL', y='GOOG',
                 trendline='ols',
                 title='Correlation between Apple and Google')
fig.show()

"""Terdapat **hubungan linier yang kuat** antara harga saham Apple dan Google, yang berarti ketika harga saham Apple meningkat maka harga saham Google juga cenderung meningkat. Ini adalah tanda korelasi atau kesamaan yang kuat antara kedua perusahaan, yang dapat disebabkan oleh faktor-faktor seperti tren industri, kondisi pasar, atau mitra bisnis atau pelanggan yang sama. Bagi investor, korelasi positif ini dapat mengindikasikan peluang untuk mendiversifikasi portofolio mereka dengan berinvestasi di kedua perusahaan, karena kedua saham tersebut menawarkan potensi pengembalian dan risiko yang serupa."""

# mencoba melihat korelasi antara Microsoft dan Netflix
# membuat DataFrame dengan harga saham Apple dan Google
microsoft = data.loc[data['Ticker'] == 'MSFT', ['Date', 'Close']].rename(columns={'Close': 'MSFT'})
netflix = data.loc[data['Ticker'] == 'NFLX', ['Date', 'Close']].rename(columns={'Close': 'NFLX'})
data_corr = pd.merge(microsoft, netflix, on='Date')

# buat scatter plot untuk memvisualisasikan korelasi
fig = px.scatter(data_corr, x='MSFT', y='NFLX',
                 trendline='ols',
                 title='Correlation between Microsoft and Netflix')
fig.show()

"""Hal yang serupa juga ditunjukkan dengan korelasi antara Microsoft dan Netflix, yang mana menunjukkan hubungan linier positif yang kuat.

#### **Ringkasan dan Kesimpulan**

4 perusahan yang kami analisa disini adalah top leading company, dimana market share mereka juga tinggi tidak hanya di spesifik negara, tapi diseluruh dunia. Dari keempat perusahaan ini juga menunjukkan grafik yang stabil terkait pergerakan nilai ddan harga saham mereka. Dengan memperhatikan nilai volatility dan rata-rata bergerak (moving averages) dari tiap perusahaan dapat menjadi acuan bagi para investor untuk melakukan tindakan kedepannya, karena kita semua tahu harga saham akan terus berubah seiring waktu.

Atas hal tersebut juga analisa lanjut perlu dilakukan untuk mengetahui performance dari semua perusahaan didalam pasar saham.
"""